INSERT INTO sch_auth.users (id, enabled, password, username, type) VALUES (8, true, '{bcrypt}$2a$10$vuC6w/TGMG1cuU9cx5N7OODyc.nE.99.bu6bS/ql1eTBhIRef1ddm', 'BaseHospitalAdmin', 2);
INSERT INTO sch_auth.users (id, enabled, password, username, type) VALUES (9, true, '{bcrypt}$2a$10$gp9f1HtSe7QHZ7aOXULds.MwIIcTnreTjpBiFJkqKFVuV5zgSBGLu', 'liyanarachi', 3);
INSERT INTO sch_auth.users (id, enabled, password, username, type) VALUES (10, true, '{bcrypt}$2a$10$t74nhcvRUh.zVRj8lgEW0eg1oHdN/wec1c2rakuAQtgO6RzjbkHnW', 'dinna', 4);

INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_ADD_ROOM', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_CANCEL_APPT', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_DELETE_DOC', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_DELETE_PT', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_DELETE_ROOM', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_ALL_DOC', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_ALL_PAY', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_ALL_PT', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_APPT', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_APPT_PAY', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_DOC', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_DOC_APPT', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_HOSP', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_HOSP_APPT', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_PAY', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_PT', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_PT_APPT', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_ROOM', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_REFUND_PAY', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_REG_DOC', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_REG_PT', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_UPDATE_APPT', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_UPDATE_DOC', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_UPDATE_HOSP', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_UPDATE_PT', 'BaseHospitalAdmin');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_UPDATE_ROOM', 'BaseHospitalAdmin');

INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_ALL_DOC', 'dinna');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_ALL_HOSP', 'dinna');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_APPT_PAY', 'dinna');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_DOC', 'dinna');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_HOSP', 'dinna');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_PT', 'dinna');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_PT_APPT', 'dinna');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_ROOM', 'dinna');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_MAKE_APPT', 'dinna');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_MAKE_PAY', 'dinna');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_REG_PT', 'dinna');

INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_ALL_HOSP', 'liyanarachi');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_ALL_PT', 'liyanarachi');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_APPT', 'liyanarachi');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_APPT_PAY', 'liyanarachi');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_DOC', 'liyanarachi');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_DOC_APPT', 'liyanarachi');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_HOSP', 'liyanarachi');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_PT', 'liyanarachi');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_PT_APPT', 'liyanarachi');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_GET_ROOM', 'liyanarachi');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_REG_DOC', 'liyanarachi');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_REG_PT', 'liyanarachi');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_UPDATE_DOC', 'liyanarachi');
INSERT INTO sch_auth.authorities (authority, username) VALUES ('ROLE_UPDATE_PT', 'liyanarachi');